### ISSUE TITLE
lags for 2-3 seconds after using the /email recovery <mail> command

### ISSUE THREAD

**Issue by Pluginsel** [AuthMe/AuthMeReloaded#1435]
If the player uses the /email recovery <email> command, the Server is will lag for 2-3 seconds.

**Comment by sgdc3** [comment]
@ljacqu any idea? the command execution should already be async

**Comment by ljacqu** [comment]
I'll have a look :) I've observed the same  thing when I have host or SSL issues in my email details—there's a noticeable lag.

**Comment by Pluginsel** [comment]
@ljacqu Any results? I waiting this for 5.5 version because is important.

**Comment by sgdc3** [comment]
Could you send us a timing report?

**Comment by Pluginsel** [comment]
@sgdc3 https://timings.spigotmc.org/?url=govosiceve

**Comment by sgdc3** [comment]
@ljacqu What do you think?

**Comment by Pluginsel** [comment]
@ljacqu What do you think?

**Comment by ljacqu** [comment]
@ljacqu What do I think?

I'm busy today but I'll have a look tomorrow evening :smile:

**Comment by sgdc3** [comment]
Lol, ok thank you ;)

**Comment by sgdc3** [comment]
@Pluginsel should have been fixed :)

**Comment by Pluginsel** [comment]
@sgdc3 I installed and tested this on AuthMe 5.5-b1888, but isn't fixed. Did you test it?

**Comment by sgdc3** [comment]
Jenkins was ko, the build with the changes is https://ci.xephi.fr/job/AuthMeReloaded/1890

**Comment by Pluginsel** [comment]
@sgdc3 @ljacqu I have tested and is work correctly, the lag is removed!! 💃 
But can you add this feature: after used the /email recovery <mail> command, add this message to messages_en.yml: 'Sending the recovery code to your email address, please wait a few seconds.'
Because after used the /email recovery <mail> command, the 'Recovery email sent successfully!' message is dislay after 2-3 seconds. (No lags)

**Comment by sgdc3** [comment]
Please open a new issue for that

**Comment by Pluginsel** [comment]
Okay, thanks for hard works. I will add on
