### ISSUE TITLE
Authme keeps downloading new Geo IP database! (On player join)

### ISSUE THREAD

**Issue by DrOreo002** [AuthMe/AuthMeReloaded#1581]
### What behaviour is observed:
Title said it all.

### Steps/models to reproduce:
I'm not really sure...

### Plugin list:
I don't think this is important.

### Environment description
Spigot 1.12.2

### AuthMe build number:
AuthMeReloaded v5.5.0-SNAPSHOT (build: 2077)

### Error Log:
Nope.

### Configuration:
Do you really need this?. Because I think the problem is on the code

**Comment by games647** [comment]
On every player join? Could you post the log where those messages are.

**Comment by AfkF24** [comment]
Same issue. Had to disable this feature completely.

```
[Player join]
[06:06:11] [Craft Scheduler Thread - 141/INFO]: [AuthMe] Downloading GEO IP database, because the old database is outdated or doesn't exist
[Disconnected]
[06:06:12] [Craft Scheduler Thread - 141/INFO]: [AuthMe] Successfully downloaded new GEO IP database to plugins/AuthMe/GeoLite2-Country.mmdb
[Player join]
[06:06:23] [Craft Scheduler Thread - 143/INFO]: [AuthMe] Downloading GEO IP database, because the old database is outdated or doesn't exist
[Disconnected]
[06:06:23] [Craft Scheduler Thread - 143/INFO]: [AuthMe] Successfully downloaded new GEO IP database to plugins/AuthMe/GeoLite2-Country.mmdb
```

**Comment by games647** [comment]
Yes it's because it detected that the file is older than 30 days. I assumed they publish a new update every 30 days, but this isn't true. I already fixed that, but it's weird that it starts multiple download tasks here.

**Comment by games647** [comment]
Should be fixed now. Could you verify it?

**Comment by AfkF24** [comment]
Just tried it out, the issue is still present

**Comment by DrOreo002** [comment]
Nope not working. Player still have the country banned message.

**Comment by games647** [comment]
Yes, because you already have the newest version. If there is no newer version available, there is no reason to download the same one. Just the successful flag wasn't set correctly.

**Comment by DrOreo002** [comment]
Ahh okay that make sense.

And, why did it send a country banned message?. Btw I'm from Indonesia and my player on my server too, and I've added Indonesia country ID into whitelist. But its still said that the country is banned

why?

**Comment by games647** [comment]
@DrOreo002 Do you tried the newest build? I fixed that the successful flag will be correctly set. It could be that AuthMe was stilling waiting for the download to finish.

**Comment by DrOreo002** [comment]
This one? : https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/2081/

**Comment by games647** [comment]
Yes

**Comment by DrOreo002** [comment]
Okay. I'll try it now

**Comment by DrOreo002** [comment]
Umm, nope. Player still have the country banned message ....

**Comment by games647** [comment]
@DrOreo002 Could you please do /authme debug cty IP?

**Comment by AfkF24** [comment]
Yeah, still not working.

```
>authme debug cty AfkF24
[11:01:00 INFO]: AuthMe country lookup
[11:01:00 INFO]: Player 'AfkF24' has IP address <ip>
[11:01:00 INFO]: IP '<ip>' maps to country '--' (N/A)
[11:01:00 INFO]: This IP address' country is blocked from the server
```

**Comment by DrOreo002** [comment]
Done. And then?

**Comment by DrOreo002** [comment]
@games647 tried it. Same result as above

**Comment by AfkF24** [comment]
Yup, fixed with the last commit!

**Comment by DrOreo002** [comment]
Thanks!. Its working fine now!
